// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARZ6T5jH4hNMl5O-_DKmc2FVi40TDDnlI',
    appId: '1:694625798838:web:a31631503dbc818cfab417',
    messagingSenderId: '694625798838',
    projectId: 'flutter-labs-cb188',
    authDomain: 'flutter-labs-cb188.firebaseapp.com',
    storageBucket: 'flutter-labs-cb188.firebasestorage.app',
    measurementId: 'G-XSWDLYJPXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnT0qiT1JcHLN6HlmLA_Lcg5wQCDWGLa8',
    appId: '1:694625798838:android:6f1750b487eb85c2fab417',
    messagingSenderId: '694625798838',
    projectId: 'flutter-labs-cb188',
    storageBucket: 'flutter-labs-cb188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXBz6HjMmk0iFOH9rQbzR8pyTdXEgv_4',
    appId: '1:694625798838:ios:e7b4a3655f3cd74ffab417',
    messagingSenderId: '694625798838',
    projectId: 'flutter-labs-cb188',
    storageBucket: 'flutter-labs-cb188.firebasestorage.app',
    iosBundleId: 'com.example.readingTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXBz6HjMmk0iFOH9rQbzR8pyTdXEgv_4',
    appId: '1:694625798838:ios:e7b4a3655f3cd74ffab417',
    messagingSenderId: '694625798838',
    projectId: 'flutter-labs-cb188',
    storageBucket: 'flutter-labs-cb188.firebasestorage.app',
    iosBundleId: 'com.example.readingTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARZ6T5jH4hNMl5O-_DKmc2FVi40TDDnlI',
    appId: '1:694625798838:web:4204cd194c53aacbfab417',
    messagingSenderId: '694625798838',
    projectId: 'flutter-labs-cb188',
    authDomain: 'flutter-labs-cb188.firebaseapp.com',
    storageBucket: 'flutter-labs-cb188.firebasestorage.app',
    measurementId: 'G-NBDXQKHM3T',
  );

}